version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mangaDb
    environment:
      POSTGRES_DB: mangadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - manga_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  manga_db:
