spring.application.name=manga-reader
server.port=9000

# DataBase Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mangadb
spring.datasource.username=postgres
spring.datasource.password=password
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# i18n Configuration
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# Springdoc configuration
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docsss
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# JWT Key
jwt.secret=i6BZ1QVBL2rehcZzSdMaLtXjH06WqSWmDZJV7Rr9+F+D2YbI5LZaOEsqObZPSrxLzgy5OhFiYY5/OexOVFV8cw==
jwt.expiration=864000000

# email service configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

token.verification.expiration=24
token.password.expiration=1

spring.task.scheduling.pool.size=5

# SSL Config
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=}
server.ssl.key-store-password=}
server.ssl.key-alias=